'use client';

import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Bot, FileText } from 'lucide-react';

export default function TermsPage() {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: `By accessing or using GoBot ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. We reserve the right to modify these terms at any time, and your continued use of the Service constitutes acceptance of any changes.`
    },
    {
      title: '2. Description of Service',
      content: `GoBot is an AI-powered development tool that integrates with Jira to help convert tickets into working code. The Service includes ticket analysis, code generation, and related features based on your subscription plan.`
    },
    {
      title: '3. User Accounts',
      content: `You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information when creating an account. You agree to notify us immediately of any unauthorized use of your account.`
    },
    {
      title: '4. Subscription & Billing',
      content: `Paid subscriptions are billed monthly in advance. All fees are non-refundable except as expressly set forth in our 30-day money-back guarantee. You may cancel your subscription at any time, and cancellation will take effect at the end of your current billing period. We reserve the right to change pricing with 30 days notice.`
    },
    {
      title: '5. Acceptable Use',
      content: `You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to any part of the Service; (c) interfere with or disrupt the Service; (d) reverse engineer or attempt to extract source code; (e) use the Service to generate malicious code or content that violates third-party rights.`
    },
    {
      title: '6. Intellectual Property',
      content: `The Service and its original content, features, and functionality are owned by GoBot and are protected by international copyright, trademark, and other intellectual property laws. Code generated by the Service for your use belongs to you, subject to any third-party licenses that may apply.`
    },
    {
      title: '7. AI-Generated Content',
      content: `The Service uses artificial intelligence to generate code and suggestions. While we strive for accuracy, AI-generated content may contain errors or be incomplete. You are responsible for reviewing, testing, and validating all generated code before use in production environments.`
    },
    {
      title: '8. Privacy & Data',
      content: `Your use of the Service is also governed by our Privacy Policy. By using the Service, you consent to the collection and use of information as described in our Privacy Policy. We process ticket data to provide the Service but do not claim ownership of your content.`
    },
    {
      title: '9. Limitation of Liability',
      content: `To the maximum extent permitted by law, GoBot shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.`
    },
    {
      title: '10. Disclaimer of Warranties',
      content: `The Service is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.`
    },
    {
      title: '11. Termination',
      content: `We may terminate or suspend your account and access to the Service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason at our sole discretion.`
    },
    {
      title: '12. Governing Law',
      content: `These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the courts of Delaware.`
    },
    {
      title: '13. Contact',
      content: `If you have any questions about these Terms, please contact us at legal@gobot.dev.`
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Background Effects */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 -left-40 w-96 h-96 bg-emerald-500/20 rounded-full blur-3xl" />
        <div className="absolute top-40 -right-40 w-96 h-96 bg-cyan-500/20 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-1/2 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl" />
      </div>
      <div className="fixed inset-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] pointer-events-none" />

      {/* Header */}
      <header className="relative z-10 border-b border-slate-800">
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <a href="/" className="flex items-center gap-2">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-cyan-500 flex items-center justify-center">
                <Bot className="w-6 h-6 text-white" />
              </div>
              <span className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 to-cyan-400">
                GoBot
              </span>
            </a>
            <Button variant="ghost" className="text-slate-300 hover:text-white" onClick={() => window.location.href = '/'}>
              ← Back
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-16 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-4xl mx-auto"
        >
          {/* Page Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-emerald-500/20 to-cyan-500/20 border border-emerald-500/30 mb-6">
              <FileText className="w-8 h-8 text-emerald-400" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Terms of Service
            </h1>
            <p className="text-slate-400">
              Last updated: January 2025
            </p>
          </div>

          {/* Terms Content */}
          <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-8 md:p-12">
            <div className="prose prose-invert max-w-none">
              <p className="text-slate-300 text-lg leading-relaxed mb-8">
                Welcome to GoBot. These Terms of Service govern your use of our AI-powered development tools and services. Please read them carefully.
              </p>

              <div className="space-y-8">
                {sections.map((section, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.05 }}
                  >
                    <h2 className="text-xl font-semibold text-white mb-3">
                      {section.title}
                    </h2>
                    <p className="text-slate-300 leading-relaxed">
                      {section.content}
                    </p>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>

          {/* Back to Home */}
          <div className="text-center mt-12">
            <Button
              onClick={() => window.location.href = '/'}
              className="bg-gradient-to-r from-emerald-600 to-cyan-600 hover:opacity-90"
            >
              Back to Home
            </Button>
          </div>
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="py-12 border-t border-slate-800 relative z-10 mt-20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-cyan-500 flex items-center justify-center">
                <Bot className="w-5 h-5 text-white" />
              </div>
              <span className="text-slate-400 text-sm">© 2025 GoBot. All rights reserved.</span>
            </div>
            <div className="flex gap-6 text-sm">
              <a href="/terms" className="text-emerald-400 hover:text-emerald-300 transition">Terms</a>
              <a href="/privacy" className="text-slate-400 hover:text-white transition">Privacy</a>
              <a href="/support" className="text-slate-400 hover:text-white transition">Support</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}